### ISSUE TITLE
Story 12 - As an iDayDream administrator, I can view a list of quick links when I go to a team site so that I can easily access the various pages in the site.

### ISSUE THREAD

**Issue by MrDrennan** [orovinskiy/IDayDream#46]
Acceptance criteria:

- [x] Given an admin visiting a team site, when they look at the contents they will see hyperlinks to:
- The volunteer form
- The volunteer summary page
- The welcome (dreamer) form
- The welcome (dreamer) summary page

**Comment by grjk** [comment]
Claimed & completed, ready for review

**Comment by grjk** [comment]
Issue completed
