### ISSUE TITLE
Story 15 -  As an iDayDream admin, I can flag a youth dreamer as “act ive” or not so that I can quickly filter out just the kids who are currently in the program.

### ISSUE THREAD

**Issue by MrDrennan** [orovinskiy/IDayDream#50]
- [x] Given a Dreamer fills out a Welcome form, when the form is submitted then the Dreamer will be marked as “pending”

- [x] Given an admin is viewing the Dreamer Summary page, when they type a status into the search field then they should see only the Dreamers with that status

- [x] Given an admin on the Summary page, when they change the status of a Dreamer, then the new status will be saved

**Comment by orovinskiy** [comment]
finished by using chads code
