### ISSUE TITLE
As an iDayDream admin, I need to log in before I can view a Summary page or the email form, so that I can keep the data secure.

### ISSUE THREAD

**Issue by orovinskiy** [orovinskiy/IDayDream#75]
- [ ] Given a non-logged in user, when they navigate to the Dreamer or Volunteer summary page, or to the email form, then they will be redirected to a login form.

- [ ] Given an admin on the login form, when they enter username: admin and password: iD@yDr3@m then they will be taken to an admin page with links to the Dreamer and Volunteer pages

- [ ] Given an admin on the login form, if they enter an incorrect username or password then they will see an “Incorrect login” message and the login form will be re-displayed

- [ ] Given a logged in user tries to navigate directly to the Volunteer or Dreamer Summary pages, then they should be able to visit those pages

**Comment by orovinskiy** [comment]
- [ ] Given a non-logged in user, when they navigate to the Dreamer or Volunteer summary page, or to the email form, then they will be redirected to a login form.
- [ ] Given an admin on the login form, when they enter username: admin and password: iD@yDr3@m then they will be taken to an admin page with links to the Dreamer and Volunteer pages
- [ ] Given an admin on the login form, if they enter an incorrect username or password then they will see an “Incorrect login” message and the login form will be re-displayed
- [ ] Given a logged in user tries to navigate directly to the Volunteer or Dreamer Summary pages, then they should be able to visit those pages

**Comment by grjk** [comment]
Completed.
